name = "distracted-drivers-keras"
repo = "https://github.com/fomorians/distracted-drivers-keras.git"
description = "State Farm Distracted Driver Challenge"
environment = "tensorflow"

[datasets]
"distracted-drivers-keras" = "0.0.2"
